import re
with open('src/backend/fyra/fyra_builtin_functions.cpp', 'r') as f: content = f.read()
content = content.replace('if (module->getFunction(\"lm_box_string\")) return;', 'ir::Function* box_string = module->getFunction(\"lm_box_string\");\\n    if (!box_string) box_string = builder->createFunction(\"lm_box_string\", context->getIntegerType(64), {context->getIntegerType(64)});\\n    if (!box_string->getBasicBlocks().empty()) return;')
content = content.replace('ir::Function* box_string = builder->createFunction(\"lm_box_string\", context->getIntegerType(64), {context->getIntegerType(64)});', '')
content = content.replace('if (module->getFunction(\"lm_box_float_from_bits\")) return;', 'ir::Function* box_f = module->getFunction(\"lm_box_float_from_bits\");\\n    if (!box_f) box_f = builder->createFunction(\"lm_box_float_from_bits\", context->getIntegerType(64), {context->getIntegerType(64)});\\n    if (!box_f->getBasicBlocks().empty()) return;')
content = content.replace('ir::Function* box_f = builder->createFunction(\"lm_box_float_from_bits\", context->getIntegerType(64), {context->getIntegerType(64)});', '')
content = content.replace('if (module->getFunction(\"abs\")) return;', 'ir::Function* abs_f = module->getFunction(\"abs\");\\n    if (!abs_f) abs_f = builder->createFunction(\"abs\", context->getIntegerType(64), {context->getIntegerType(64)});\\n    if (!abs_f->getBasicBlocks().empty()) return;')
content = content.replace('ir::Function* abs_f = builder->createFunction(\"abs\", context->getIntegerType(64), {context->getIntegerType(64)});', '')
content = content.replace('if (used_builtins.count(\"lm_box_string\")) emit_box_string(module, builder);', 'if (used_builtins.count(\"lm_box_string\")) emit_box_string(module, builder);\\n    if (used_builtins.count(\"lm_box_float_from_bits\")) emit_box_float_from_bits(module, builder);')
with open('src/backend/fyra/fyra_builtin_functions.cpp', 'w') as f: f.write(content)
