import sys

with open('src/lir/generator/expressions.cpp', 'r') as f:
    lines = f.readlines()

start_line = -1
end_line = -1

for i, line in enumerate(lines):
    if 'Reg Generator::emit_call_expr(LM::Frontend::AST::CallExpr& expr) {' in line:
        start_line = i
    if 'Reg Generator::emit_assign_expr(LM::Frontend::AST::AssignExpr& expr) {' in line:
        end_line = i
        break

if start_line != -1 and end_line != -1:
    new_func = [
        'Reg Generator::emit_call_expr(LM::Frontend::AST::CallExpr& expr) {\n',
        '    if (auto var_expr = dynamic_cast<LM::Frontend::AST::VariableExpr*>(expr.callee.get())) {\n',
        '        std::string func_name = var_expr->name;\n',
        '        if (func_name == "print") {\n',
        '            std::vector<Reg> arg_regs;\n',
        '            for (const auto& arg : expr.arguments) arg_regs.push_back(emit_expr(*arg));\n',
        '            Reg result = allocate_register();\n',
        '            Reg handle_reg = allocate_register();\n',
        '            emit_instruction(LIR_Inst(LIR_Op::LoadConst, Type::I64, handle_reg, make_i64(0)));\n',
        '            Reg list_reg = allocate_register();\n',
        '            emit_instruction(LIR_Inst(LIR_Op::ListCreate, Type::Ptr, list_reg, 0, 0));\n',
        '            for (auto r : arg_regs) {\n',
        '                Reg temp = allocate_register();\n',
        '                emit_instruction(LIR_Inst(LIR_Op::ListAppend, Type::Void, temp, list_reg, r));\n',
        '            }\n',
        '            Reg newline_reg = allocate_register();\n',
        '            emit_instruction(LIR_Inst(LIR_Op::LoadConst, Type::Ptr, newline_reg, BOX_PTR(lm_box_string("\\n"))));\n',
        '            Reg temp2 = allocate_register();\n',
        '            emit_instruction(LIR_Inst(LIR_Op::ListAppend, Type::Void, temp2, list_reg, newline_reg));\n',
        '            emit_instruction(LIR_Inst(LIR_Op::ResourceCall, Type::Void, result, handle_reg, list_reg, 3));\n',
        '            set_register_language_type(result, std::make_shared<::Type>(::TypeTag::Nil));\n',
        '            return result;\n',
        '        }\n',
        '\n',
        '        std::string registry_lookup_name = func_name;\n',
        '        size_t d_pos = func_name.rfind(\'.\');\n',
        '        if (d_pos != std::string::npos) {\n',
        '            std::string mod_name = func_name.substr(0, d_pos);\n',
        '            std::string sym_name = func_name.substr(d_pos + 1);\n',
        '            auto a_it = import_aliases_.find(mod_name);\n',
        '            if (a_it != import_aliases_.end()) mod_name = a_it->second;\n',
        '            registry_lookup_name = mod_name + "." + sym_name;\n',
        '        }\n',
        '\n',
        '        if (auto intrinsic = IntrinsicRegistry::getInstance().getIntrinsic(registry_lookup_name)) {\n',
        '            std::vector<Reg> arg_regs;\n',
        '            for (const auto& arg : expr.arguments) arg_regs.push_back(emit_expr(*arg));\n',
        '            Reg result = allocate_register();\n',
        '            Type abi_res_type = Type::Void;\n',
        '            if (expr.inferred_type) {\n',
        '                set_register_language_type(result, expr.inferred_type);\n',
        '                abi_res_type = language_type_to_abi_type(expr.inferred_type);\n',
        '                set_register_abi_type(result, abi_res_type);\n',
        '            }\n',
        '            LIR_Inst inst(intrinsic->opcode, abi_res_type, result, 0, 0, 0);\n',
        '            inst.imm = intrinsic->type_id;\n',
        '            if (intrinsic->opcode == LIR_Op::ResourceCall) {\n',
        '                inst.b = UINT32_MAX;\n',
        '                if (!arg_regs.empty()) inst.a = arg_regs[0];\n',
        '                if (arg_regs.size() > 1) {\n',
        '                    if (auto lit = std::dynamic_pointer_cast<LM::Frontend::AST::LiteralExpr>(expr.arguments[1])) {\n',
        '                        if (std::holds_alternative<std::string>(lit->value)) {\n',
        '                             try { inst.imm = static_cast<uint32_t>(std::stoll(std::get<std::string>(lit->value))); }\n',
        '                             catch (...) { inst.imm = 0; }\n',
        '                        }\n',
        '                    }\n',
        '                }\n',
        '                if (arg_regs.size() > 2) inst.b = arg_regs[2];\n',
        '            } else if (intrinsic->opcode == LIR_Op::ResourceCreate) {\n',
        '                inst.b = UINT32_MAX;\n',
        '                if (!arg_regs.empty()) inst.a = arg_regs[0];\n',
        '                if (arg_regs.size() > 1) inst.b = arg_regs[1];\n',
        '            } else {\n',
        '                if (!arg_regs.empty()) inst.a = arg_regs[0];\n',
        '                if (arg_regs.size() > 1) inst.b = arg_regs[1];\n',
        '                if (arg_regs.size() > 2) for (size_t k = 2; k < arg_regs.size(); ++k) inst.call_args.push_back(arg_regs[k]);\n',
        '            }\n',
        '            emit_instruction(inst);\n',
        '            return result;\n',
        '        }\n',
        '\n',
        '        auto frame_it = frame_table_.find(func_name);\n',
        '        if (frame_it != frame_table_.end()) {\n',
        '            Reg frame_reg = allocate_register();\n',
        '            const FrameInfo& frame_info = frame_it->second;\n',
        '            LIR_Inst new_frame_inst(LIR_Op::NewFrame, Type::Ptr, frame_reg, 0, 0, static_cast<uint32_t>(frame_info.total_field_size));\n',
        '            new_frame_inst.type_name = func_name;\n',
        '            emit_instruction(new_frame_inst);\n',
        '            auto frame_type = std::make_shared<::Type>(::TypeTag::Frame);\n',
        '            FrameType ft; ft.name = func_name; frame_type->extra = ft;\n',
        '            set_register_language_type(frame_reg, frame_type); set_register_abi_type(frame_reg, Type::Ptr);\n',
        '            if (frame_info.declaration) {\n',
        '                for (size_t i = 0; i < frame_info.declaration->fields.size(); ++i) {\n',
        '                    auto field = frame_info.declaration->fields[i];\n',
        '                    Reg val_reg = field->defaultValue ? emit_expr(*field->defaultValue) : allocate_register();\n',
        '                    if (!field->defaultValue) emit_instruction(LIR_Inst(LIR_Op::LoadConst, Type::Void, val_reg, VAL_NIL));\n',
        '                    emit_instruction(LIR_Inst(LIR_Op::FrameSetField, Type::Void, frame_reg, static_cast<uint32_t>(i), val_reg));\n',
        '                }\n',
        '            }\n',
        '            for (const auto& [name, arg_expr] : expr.namedArgs) {\n',
        '                auto offset_it = frame_info.field_offsets.find(name);\n',
        '                if (offset_it != frame_info.field_offsets.end()) {\n',
        '                    Reg val_reg = emit_expr(*arg_expr);\n',
        '                    emit_instruction(LIR_Inst(LIR_Op::FrameSetField, Type::Void, frame_reg, static_cast<uint32_t>(offset_it->second), val_reg));\n',
        '                }\n',
        '            }\n',
        '            if (frame_info.has_init) {\n',
        '                std::string init_name = func_name + ".init";\n',
        '                std::vector<Reg> arg_regs; arg_regs.push_back(frame_reg);\n',
        '                for (const auto& arg : expr.arguments) arg_regs.push_back(emit_expr(*arg));\n',
        '                Reg init_result = allocate_register();\n',
        '                LIR_Inst call_inst(LIR_Op::Call, init_result, init_name, arg_regs);\n',
        '                for (Reg r : arg_regs) call_inst.call_arg_types.push_back(get_register_abi_type(r));\n',
        '                emit_instruction(call_inst);\n',
        '            }\n',
        '            if (frame_info.has_deinit && !scope_stack_.empty()) scope_stack_.back().frame_instances.push_back({func_name, frame_reg});\n',
        '            return frame_reg;\n',
        '        }\n',
        '\n',
        '        if (!current_module_.empty()) {\n',
        '            std::string qualified_func_name = current_module_ + "." + func_name;\n',
        '            if (function_table_.find(qualified_func_name) != function_table_.end()) func_name = qualified_func_name;\n',
        '        }\n',
        '\n',
        '        if (function_table_.find(func_name) != function_table_.end()) {\n',
        '            std::vector<Reg> arg_regs;\n',
        '            for (const auto& arg : expr.arguments) arg_regs.push_back(emit_expr(*arg));\n',
        '            Reg result = allocate_register();\n',
        '            emit_instruction(LIR_Inst(LIR_Op::Call, result, func_name, arg_regs));\n',
        '            return result;\n',
        '        } else if (BuiltinUtils::isBuiltinFunction(func_name)) {\n',
        '            std::vector<Reg> arg_regs;\n',
        '            for (const auto& arg : expr.arguments) arg_regs.push_back(emit_expr(*arg));\n',
        '            Reg result = allocate_register();\n',
        '            emit_instruction(LIR_Inst(LIR_Op::Call, result, func_name, arg_regs));\n',
        '            return result;\n',
        '        } else {\n',
        '            Reg var_reg = resolve_variable(func_name);\n',
        '            if (var_reg != UINT32_MAX) {\n',
        '                LM::Frontend::AST::CallClosureExpr closure_call;\n',
        '                closure_call.closure = expr.callee; closure_call.arguments = expr.arguments;\n',
        '                return emit_call_closure_expr(closure_call);\n',
        '            }\n',
        '            report_error("Unknown function: " + func_name); return 0;\n',
        '        }\n',
        '    } else if (auto member_expr = dynamic_cast<LM::Frontend::AST::MemberExpr*>(expr.callee.get())) {\n',
        '        std::string method_name = member_expr->name;\n',
        '        Reg object_reg = emit_expr(*member_expr->object);\n',
        '        std::vector<Reg> arg_regs; arg_regs.push_back(object_reg);\n',
        '        for (const auto& arg : expr.arguments) arg_regs.push_back(emit_expr(*arg));\n',
        '        Reg result = allocate_register();\n',
        '        emit_instruction(LIR_Inst(LIR_Op::Call, result, method_name, arg_regs));\n',
        '        return result;\n',
        '    } else {\n',
        '        report_error("Complex function calls not yet supported in LIR"); return 0;\n',
        '    }\n',
        '}\n'
    ]
    lines[start_line:end_line] = new_func
    with open('src/lir/generator/expressions.cpp', 'w') as f:
        f.writelines(lines)
    print("Successfully replaced emit_call_expr with true ResourceCall lowering for print")
else:
    print(f"Markers not found: start_line={start_line}, end_line={end_line}")
