import sys

with open('src/lir/generator/expressions.cpp', 'r') as f:
    lines = f.readlines()

start_line = -1
end_line = -1

for i, line in enumerate(lines):
    if 'Reg Generator::emit_call_expr(LM::Frontend::AST::CallExpr& expr) {' in line:
        start_line = i
    if 'Reg Generator::emit_assign_expr(LM::Frontend::AST::AssignExpr& expr) {' in line:
        end_line = i
        break

if start_line != -1 and end_line != -1:
    new_func = [
        'Reg Generator::emit_call_expr(LM::Frontend::AST::CallExpr& expr) {\n',
        '    if (auto var_expr = dynamic_cast<LM::Frontend::AST::VariableExpr*>(expr.callee.get())) {\n',
        '        std::string func_name = var_expr->name;\n',
        '\n',
        '        // Resolve qualified name for intrinsic lookup\n',
        '        std::string registry_lookup_name = func_name;\n',
        '        size_t d_pos = func_name.rfind(\'.\');\n',
        '        if (d_pos != std::string::npos) {\n',
        '            std::string mod_name = func_name.substr(0, d_pos);\n',
        '            std::string sym_name = func_name.substr(d_pos + 1);\n',
        '            auto a_it = import_aliases_.find(mod_name);\n',
        '            if (a_it != import_aliases_.end()) mod_name = a_it->second;\n',
        '            registry_lookup_name = mod_name + "." + sym_name;\n',
        '        }\n',
        '\n',
        '        if (auto intrinsic = IntrinsicRegistry::getInstance().getIntrinsic(registry_lookup_name)) {\n',
        '            std::vector<Reg> arg_regs;\n',
        '            for (const auto& arg : expr.arguments) arg_regs.push_back(emit_expr(*arg));\n',
        '            Reg result = allocate_register();\n',
        '            Type abi_res_type = Type::Void;\n',
        '            if (expr.inferred_type) {\n',
        '                set_register_language_type(result, expr.inferred_type);\n',
        '                abi_res_type = language_type_to_abi_type(expr.inferred_type);\n',
        '                set_register_abi_type(result, abi_res_type);\n',
        '            }\n',
        '            \n',
        '            LIR_Inst inst(intrinsic->opcode, abi_res_type, result, 0, 0, 0);\n',
        '            inst.imm = intrinsic->type_id;\n',
        '\n',
        '            if (intrinsic->opcode == LIR_Op::ResourceCall) {\n',
        '                inst.b = UINT32_MAX;\n',
        '                if (registry_lookup_name == "print") {\n',
        '                    Reg handle_reg = allocate_register();\n',
        '                    emit_instruction(LIR_Inst(LIR_Op::LoadConst, Type::I64, handle_reg, make_i64(0)));\n',
        '                    inst.a = handle_reg;\n',
        '                    inst.imm = 3; // OP_WRITE\n',
        '                    Reg list_reg = allocate_register();\n',
        '                    emit_instruction(LIR_Inst(LIR_Op::ListCreate, Type::Ptr, list_reg, 0, 0));\n',
        '                    for (auto r : arg_regs) {\n',
        '                        Reg temp = allocate_register();\n',
        '                        emit_instruction(LIR_Inst(LIR_Op::ListAppend, Type::Void, temp, list_reg, r));\n',
        '                    }\n',
        '                    Reg newline_reg = allocate_register();\n',
        '                    emit_instruction(LIR_Inst(LIR_Op::LoadConst, Type::Ptr, newline_reg, BOX_PTR(lm_box_string("\\n"))));\n',
        '                    Reg temp2 = allocate_register();\n',
        '                    emit_instruction(LIR_Inst(LIR_Op::ListAppend, Type::Void, temp2, list_reg, newline_reg));\n',
        '                    inst.b = list_reg;\n',
        '                } else if (arg_regs.size() >= 2) {\n',
        '                    inst.a = arg_regs[0];\n',
        '                    if (auto lit = std::dynamic_pointer_cast<LM::Frontend::AST::LiteralExpr>(expr.arguments[1])) {\n',
        '                        if (std::holds_alternative<std::string>(lit->value)) {\n',
        '                             try {\n',
        '                                 inst.imm = static_cast<uint32_t>(std::stoll(std::get<std::string>(lit->value)));\n',
        '                             } catch (...) { inst.imm = 0; }\n',
        '                        }\n',
        '                    }\n',
        '                    if (arg_regs.size() > 2) inst.b = arg_regs[2];\n',
        '                }\n',
        '            } else if (intrinsic->opcode == LIR_Op::ResourceCreate) {\n',
        '                inst.b = UINT32_MAX;\n',
        '                if (!arg_regs.empty()) inst.a = arg_regs[0];\n',
        '                if (arg_regs.size() > 1) inst.b = arg_regs[1];\n',
        '            } else {\n',
        '                if (!arg_regs.empty()) inst.a = arg_regs[0];\n',
        '                if (arg_regs.size() > 1) {\n',
        '                    inst.b = arg_regs[1];\n',
        '                    if (intrinsic->opcode == LIR_Op::MemoryStore) {\n',
        '                        TypePtr val_type = (expr.arguments.size() > 1) ? get_register_language_type(arg_regs[1]) : nullptr;\n',
        '                        inst.type_b = language_type_to_abi_type(val_type);\n',
        '                    }\n',
        '                }\n',
        '                if (arg_regs.size() > 2) {\n',
        '                    for (size_t k = 2; k < arg_regs.size(); ++k) inst.call_args.push_back(arg_regs[k]);\n',
        '                }\n',
        '            }\n',
        '            emit_instruction(inst);\n',
        '            return result;\n',
        '        }\n',
        '\n',
        '        if (expr.inferred_type && expr.inferred_type->tag == ::TypeTag::Frame) {\n',
        '            FrameType ft = std::get<FrameType>(expr.inferred_type->extra);\n',
        '            func_name = ft.name;\n',
        '        }\n',
        '\n',
        '        auto frame_it = frame_table_.find(func_name);\n',
        '        if (frame_it == frame_table_.end()) {\n',
        '            int64_t tag = 0; size_t expected_arity = 0;\n',
        '            TypePtr enum_hint = expr.inferred_type;\n',
        '            if (func_name.find(\'.\') != std::string::npos && type_system_) {\n',
        '                 auto name = func_name.substr(0, func_name.find(\'.\'));\n',
        '                 auto found = type_system_->getType(name);\n',
        '                 if (found && (found->tag == TypeTag::Enum || found->tag == TypeTag::UserDefined)) enum_hint = found;\n',
        '            }\n',
        '            bool resolved = resolve_enum_variant_info(type_system_.get(), enum_hint, func_name, tag, expected_arity);\n',
        '            if (!resolved && enum_hint && (enum_hint->tag == TypeTag::Enum || enum_hint->tag == TypeTag::UserDefined || enum_hint->tag == TypeTag::Frame)) {\n',
        '                if (auto* et = std::get_if<EnumType>(&enum_hint->extra)) {\n',
        '                    resolved = resolve_enum_variant_info(type_system_.get(), enum_hint, et->name + "." + func_name, tag, expected_arity);\n',
        '                }\n',
        '            }\n',
        '            if (resolved) {\n',
        '                Reg payload_reg = UINT32_MAX;\n',
        '                if (expr.arguments.size() == 1) {\n',
        '                    payload_reg = emit_expr(*expr.arguments[0]);\n',
        '                } else if (expr.arguments.size() > 1) {\n',
        '                    payload_reg = allocate_register();\n',
        '                    emit_instruction(LIR_Inst(LIR_Op::TupleCreate, Type::Ptr, payload_reg, 0, 0, (uint32_t)expr.arguments.size()));\n',
        '                    for (size_t i = 0; i < expr.arguments.size(); ++i) {\n',
        '                        Reg arg_reg = emit_expr(*expr.arguments[i]);\n',
        '                        Reg idx_reg = allocate_register();\n',
        '                        emit_instruction(LIR_Inst(LIR_Op::LoadConst, Type::I64, idx_reg, make_i64(i)));\n',
        '                        emit_instruction(LIR_Inst(LIR_Op::TupleSet, Type::Void, payload_reg, idx_reg, arg_reg));\n',
        '                    }\n',
        '                }\n',
        '                Reg result = allocate_register();\n',
        '                LIR_Inst make_enum_inst(LIR_Op::MakeEnum, Type::Ptr, result, payload_reg, 0, (uint32_t)tag);\n',
        '                emit_instruction(make_enum_inst);\n',
        '                if (expr.inferred_type) set_register_language_type(result, expr.inferred_type);\n',
        '                return result;\n',
        '            }\n',
        '        }\n',
        '\n',
        '        if (frame_it != frame_table_.end()) {\n',
        '            Reg frame_reg = allocate_register();\n',
        '            const FrameInfo& frame_info = frame_it->second;\n',
        '            LIR_Inst new_frame_inst(LIR_Op::NewFrame, Type::Ptr, frame_reg, 0, 0, static_cast<uint32_t>(frame_info.total_field_size));\n',
        '            new_frame_inst.type_name = func_name;\n',
        '            emit_instruction(new_frame_inst);\n',
        '            auto frame_type = std::make_shared<::Type>(::TypeTag::Frame);\n',
        '            FrameType ft; ft.name = func_name; frame_type->extra = ft;\n',
        '            set_register_language_type(frame_reg, frame_type);\n',
        '            set_register_abi_type(frame_reg, Type::Ptr);\n',
        '            if (frame_info.declaration) {\n',
        '                for (size_t i = 0; i < frame_info.declaration->fields.size(); ++i) {\n',
        '                    auto field = frame_info.declaration->fields[i];\n',
        '                    Reg val_reg = field->defaultValue ? emit_expr(*field->defaultValue) : allocate_register();\n',
        '                    if (!field->defaultValue) emit_instruction(LIR_Inst(LIR_Op::LoadConst, Type::Void, val_reg, VAL_NIL));\n',
        '                    emit_instruction(LIR_Inst(LIR_Op::FrameSetField, Type::Void, frame_reg, static_cast<uint32_t>(i), val_reg));\n',
        '                }\n',
        '            }\n',
        '            for (const auto& [name, arg_expr] : expr.namedArgs) {\n',
        '                auto offset_it = frame_info.field_offsets.find(name);\n',
        '                if (offset_it != frame_info.field_offsets.end()) {\n',
        '                    Reg val_reg = emit_expr(*arg_expr);\n',
        '                    emit_instruction(LIR_Inst(LIR_Op::FrameSetField, Type::Void, frame_reg, static_cast<uint32_t>(offset_it->second), val_reg));\n',
        '                }\n',
        '            }\n',
        '            if (frame_info.has_init) {\n',
        '                std::string init_name = func_name + ".init";\n',
        '                std::vector<Reg> arg_regs; arg_regs.push_back(frame_reg);\n',
        '                std::unordered_set<std::string> consumed_named_args;\n',
        '                if (frame_info.declaration && frame_info.declaration->init) {\n',
        '                    const auto& init = frame_info.declaration->init;\n',
        '                    size_t pos_idx = 0;\n',
        '                    for (; pos_idx < expr.arguments.size() && pos_idx < init->parameters.size(); ++pos_idx) arg_regs.push_back(emit_expr(*expr.arguments[pos_idx]));\n',
        '                    for (; pos_idx < init->parameters.size(); ++pos_idx) {\n',
        '                        const std::string& param_name = init->parameters[pos_idx].first;\n',
        '                        auto it = expr.namedArgs.find(param_name);\n',
        '                        if (it != expr.namedArgs.end()) { arg_regs.push_back(emit_expr(*it->second)); consumed_named_args.insert(param_name); }\n',
        '                        else { Reg nil_reg = allocate_register(); emit_instruction(LIR_Inst(LIR_Op::LoadConst, Type::Void, nil_reg, VAL_NIL)); arg_regs.push_back(nil_reg); }\n',
        '                    }\n',
        '                    for (size_t i = 0; i < init->optionalParams.size(); ++i) {\n',
        '                        const std::string& param_name = init->optionalParams[i].first;\n',
        '                        auto it = expr.namedArgs.find(param_name);\n',
        '                        if (it != expr.namedArgs.end()) { arg_regs.push_back(emit_expr(*it->second)); consumed_named_args.insert(param_name); }\n',
        '                        else if (expr.arguments.size() > pos_idx) arg_regs.push_back(emit_expr(*expr.arguments[pos_idx++]));\n',
        '                        else if (init->optionalParams[i].second.second) arg_regs.push_back(emit_expr(*init->optionalParams[i].second.second));\n',
        '                        else { Reg nil_reg = allocate_register(); emit_instruction(LIR_Inst(LIR_Op::LoadConst, Type::Void, nil_reg, VAL_NIL)); arg_regs.push_back(nil_reg); }\n',
        '                    }\n',
        '                } else { for (const auto& arg : expr.arguments) arg_regs.push_back(emit_expr(*arg)); }\n',
        '                Reg init_result = allocate_register();\n',
        '                LIR_Inst call_inst(LIR_Op::Call, init_result, init_name, arg_regs);\n',
        '                for (Reg r : arg_regs) call_inst.call_arg_types.push_back(get_register_abi_type(r));\n',
        '                emit_instruction(call_inst);\n',
        '                for (const auto& [name, arg_expr] : expr.namedArgs) {\n',
        '                    if (consumed_named_args.count(name)) continue;\n',
        '                    auto offset_it = frame_info.field_offsets.find(name);\n',
        '                    if (offset_it != frame_info.field_offsets.end()) {\n',
        '                        Reg val_reg = emit_expr(*arg_expr);\n',
        '                        emit_instruction(LIR_Inst(LIR_Op::FrameSetField, Type::Void, frame_reg, static_cast<uint32_t>(offset_it->second), val_reg));\n',
        '                    }\n',
        '                }\n',
        '            }\n',
        '            if (frame_info.has_deinit && !scope_stack_.empty()) scope_stack_.back().frame_instances.push_back({func_name, frame_reg});\n',
        '            return frame_reg;\n',
        '        }\n',
        '\n',
        '        if (!current_module_.empty()) {\n',
        '            std::string qualified_func_name = current_module_ + "." + func_name;\n',
        '            if (function_table_.find(qualified_func_name) != function_table_.end()) func_name = qualified_func_name;\n',
        '        }\n',
        '\n',
        '        if (function_table_.find(func_name) != function_table_.end()) {\n',
        '            std::vector<Reg> arg_regs;\n',
        '            for (const auto& arg : expr.arguments) arg_regs.push_back(emit_expr(*arg));\n',
        '            Reg result = allocate_register();\n',
        '            if (expr.inferred_type) {\n',
        '                set_register_language_type(result, expr.inferred_type);\n',
        '                set_register_abi_type(result, language_type_to_abi_type(expr.inferred_type));\n',
        '            } else {\n',
        '                auto any_type = std::make_shared<::Type>(::TypeTag::Any);\n',
        '                set_register_language_type(result, any_type);\n',
        '                set_register_abi_type(result, language_type_to_abi_type(any_type));\n',
        '            }\n',
        '            emit_instruction(LIR_Inst(LIR_Op::Call, result, func_name, arg_regs));\n',
        '            return result;\n',
        '        } else if (BuiltinUtils::isBuiltinFunction(func_name)) {\n',
        '            if (func_name == "channel") {\n',
        '                Reg result = allocate_register();\n',
        '                auto channel_type = std::make_shared<::Type>(::TypeTag::Channel);\n',
        '                set_register_language_type(result, channel_type); set_register_abi_type(result, Type::Ptr);\n',
        '                emit_instruction(LIR_Inst(LIR_Op::ChannelAlloc, Type::Ptr, result, 0, 0));\n',
        '                return result;\n',
        '            }\n',
        '            std::vector<Reg> arg_regs;\n',
        '            for (const auto& arg : expr.arguments) arg_regs.push_back(emit_expr(*arg));\n',
        '            Reg result = allocate_register();\n',
        '            if (expr.inferred_type) {\n',
        '                set_register_language_type(result, expr.inferred_type);\n',
        '                set_register_abi_type(result, language_type_to_abi_type(expr.inferred_type));\n',
        '            } else {\n',
        '                auto any_type = std::make_shared<::Type>(::TypeTag::Any);\n',
        '                set_register_language_type(result, any_type);\n',
        '                set_register_abi_type(result, language_type_to_abi_type(any_type));\n',
        '            }\n',
        '            emit_instruction(LIR_Inst(LIR_Op::Call, result, func_name, arg_regs));\n',
        '            return result;\n',
        '        } else {\n',
        '            Reg var_reg = resolve_variable(func_name);\n',
        '            bool captured_function = (env_register_ != UINT32_MAX) && std::find(current_lambda_captures_.begin(), current_lambda_captures_.end(), func_name) != current_lambda_captures_.end();\n',
        '            if (var_reg != UINT32_MAX || captured_function) {\n',
        '                LM::Frontend::AST::CallClosureExpr closure_call;\n',
        '                closure_call.closure = expr.callee; closure_call.arguments = expr.arguments; closure_call.namedArgs = expr.namedArgs; closure_call.inferred_type = expr.inferred_type;\n',
        '                return emit_call_closure_expr(closure_call);\n',
        '            }\n',
        '            report_error("Unknown function: " + func_name); return 0;\n',
        '        }\n',
        '    } else if (auto member_expr = dynamic_cast<LM::Frontend::AST::MemberExpr*>(expr.callee.get())) {\n',
        '        std::string method_name = member_expr->name;\n',
        '        if (auto enum_obj = dynamic_cast<LM::Frontend::AST::VariableExpr*>(member_expr->object.get())) {\n',
        '            int64_t tag = 0; size_t expected_arity = 0;\n',
        '            std::string qualified_variant = enum_obj->name + "." + method_name;\n',
        '            TypePtr enum_hint = member_expr->object->inferred_type;\n',
        '            if ((!enum_hint || enum_hint->tag != TypeTag::Enum) && type_system_) enum_hint = type_system_->getType(enum_obj->name);\n',
        '            if (resolve_enum_variant_info(type_system_.get(), enum_hint, qualified_variant, tag, expected_arity)) {\n',
        '                Reg result = allocate_register(); Reg payload = UINT32_MAX;\n',
        '                if (!expr.arguments.empty()) {\n',
        '                    if (expr.arguments.size() == 1) payload = emit_expr(*expr.arguments[0]);\n',
        '                    else {\n',
        '                        Reg tuple_reg = allocate_register();\n',
        '                        emit_instruction(LIR_Inst(LIR_Op::TupleCreate, Type::Ptr, tuple_reg, 0, 0, static_cast<uint32_t>(expr.arguments.size())));\n',
        '                        for (size_t i = 0; i < expr.arguments.size(); ++i) {\n',
        '                            Reg arg_reg = emit_expr(*expr.arguments[i]);\n',
        '                            Reg idx_reg = allocate_register(); emit_instruction(LIR_Inst(LIR_Op::LoadConst, Type::I64, idx_reg, make_i64(i)));\n',
        '                            emit_instruction(LIR_Inst(LIR_Op::TupleSet, Type::Ptr, tuple_reg, idx_reg, arg_reg));\n',
        '                        }\n',
        '                        payload = tuple_reg;\n',
        '                    }\n',
        '                }\n',
        '                emit_instruction(LIR_Inst(LIR_Op::MakeEnum, Type::Ptr, result, payload, 0, static_cast<uint32_t>(tag)));\n',
        '                if (expr.inferred_type) { set_register_language_type(result, expr.inferred_type); set_register_abi_type(result, Type::Ptr); }\n',
        '                return result;\n',
        '            }\n',
        '        }\n',
        '        if (auto var_expr = dynamic_cast<LM::Frontend::AST::VariableExpr*>(member_expr->object.get())) {\n',
        '            auto alias_it = import_aliases_.find(var_expr->name);\n',
        '            if (alias_it != import_aliases_.end()) {\n',
        '                std::string qualified_name = alias_it->second + "." + method_name;\n',
        '                std::vector<Reg> arg_regs;\n',
        '                for (const auto& arg : expr.arguments) arg_regs.push_back(emit_expr(*arg));\n',
        '                Reg result = allocate_register(); Type abi_res_type = Type::Void;\n',
        '                if (expr.inferred_type) {\n',
        '                    set_register_language_type(result, expr.inferred_type);\n',
        '                    abi_res_type = language_type_to_abi_type(expr.inferred_type);\n',
        '                    set_register_abi_type(result, abi_res_type);\n',
        '                }\n',
        '                if (auto intrinsic = IntrinsicRegistry::getInstance().getIntrinsic(qualified_name)) {\n',
        '                    LIR_Inst inst(intrinsic->opcode, abi_res_type, result, 0, 0, 0);\n',
        '                    inst.imm = intrinsic->type_id;\n',
        '                    if (intrinsic->opcode == LIR_Op::ResourceCall) {\n',
        '                        inst.b = UINT32_MAX;\n',
        '                        if (qualified_name == "print") {\n',
        '                             Reg handle_reg = allocate_register();\n',
        '                             emit_instruction(LIR_Inst(LIR_Op::LoadConst, Type::I64, handle_reg, make_i64(0)));\n',
        '                             inst.a = handle_reg; inst.imm = 3; \n',
        '                             Reg list_reg = allocate_register();\n',
        '                             emit_instruction(LIR_Inst(LIR_Op::ListCreate, Type::Ptr, list_reg, 0, 0));\n',
        '                             for (auto r : arg_regs) { Reg temp = allocate_register(); emit_instruction(LIR_Inst(LIR_Op::ListAppend, Type::Void, temp, list_reg, r)); }\n',
        '                             Reg newline_reg = allocate_register();\n',
        '                             emit_instruction(LIR_Inst(LIR_Op::LoadConst, Type::Ptr, newline_reg, BOX_PTR(lm_box_string("\\n"))));\n',
        '                             Reg temp2 = allocate_register(); emit_instruction(LIR_Inst(LIR_Op::ListAppend, Type::Void, temp2, list_reg, newline_reg));\n',
        '                             inst.b = list_reg;\n',
        '                        } else if (arg_regs.size() >= 2) {\n',
        '                            inst.a = arg_regs[0];\n',
        '                            if (auto lit = std::dynamic_pointer_cast<LM::Frontend::AST::LiteralExpr>(expr.arguments[1])) {\n',
        '                                if (std::holds_alternative<std::string>(lit->value)) { try { inst.imm = static_cast<uint32_t>(std::stoll(std::get<std::string>(lit->value))); } catch (...) { inst.imm = 0; } }\n',
        '                            }\n',
        '                            if (arg_regs.size() > 2) inst.b = arg_regs[2];\n',
        '                        }\n',
        '                    } else if (intrinsic->opcode == LIR_Op::ResourceCreate) {\n',
        '                        inst.b = UINT32_MAX;\n',
        '                        if (!arg_regs.empty()) inst.a = arg_regs[0];\n',
        '                        if (arg_regs.size() > 1) inst.b = arg_regs[1];\n',
        '                    } else {\n',
        '                        if (!arg_regs.empty()) inst.a = arg_regs[0];\n',
        '                        if (arg_regs.size() > 1) inst.b = arg_regs[1];\n',
        '                        if (arg_regs.size() > 2) for (size_t k = 2; k < arg_regs.size(); ++k) inst.call_args.push_back(arg_regs[k]);\n',
        '                    }\n',
        '                    emit_instruction(inst);\n',
        '                    return result;\n',
        '                }\n',
        '                emit_instruction(LIR_Inst(LIR_Op::Call, result, qualified_name, arg_regs));\n',
        '                return result;\n',
        '            }\n',
        '        }\n',
        '        Reg object_reg = emit_expr(*member_expr->object);\n',
        '        std::vector<Reg> arg_regs; arg_regs.push_back(object_reg);\n',
        '        for (const auto& arg : expr.arguments) arg_regs.push_back(emit_expr(*arg));\n',
        '        TypePtr object_type = member_expr->object->inferred_type;\n',
        '        if (object_type && object_type->tag == TypeTag::Frame) {\n',
        '            auto frame_type_info = std::get_if<FrameType>(&object_type->extra);\n',
        '            if (frame_type_info) {\n',
        '                std::string frame_name = frame_type_info->name;\n',
        '                auto it = frame_table_.find(frame_name);\n',
        '                if (it != frame_table_.end()) {\n',
        '                    const FrameInfo& frame_info = it->second;\n',
        '                    auto method_it = frame_info.method_indices.find(method_name);\n',
        '                    if (method_it != frame_info.method_indices.end()) {\n',
        '                        std::string full_method_name = frame_name + "." + method_name;\n',
        '                        Reg result = allocate_register();\n',
        '                        if (expr.inferred_type) { set_register_language_type(result, expr.inferred_type); set_register_abi_type(result, language_type_to_abi_type(expr.inferred_type)); }\n',
        '                        LIR_Inst call_inst(LIR_Op::Call, result, full_method_name, arg_regs);\n',
        '                        for (Reg r : arg_regs) call_inst.call_arg_types.push_back(get_register_abi_type(r));\n',
        '                        emit_instruction(call_inst); return result;\n',
        '                    }\n',
        '                }\n',
        '            }\n',
        '        }\n',
        '        if (method_name == "send") {\n',
        '            Reg value_reg = emit_expr(*expr.arguments[0]); Reg result = allocate_register();\n',
        '            emit_instruction(LIR_Inst(LIR_Op::ChannelSend, result, object_reg, value_reg));\n',
        '            set_register_type(result, std::make_shared<::Type>(::TypeTag::Nil)); return result;\n',
        '        }\n',
        '        if (method_name == "recv") {\n',
        '            Reg result = allocate_register(); emit_instruction(LIR_Inst(LIR_Op::ChannelRecv, result, object_reg));\n',
        '            set_register_type(result, std::make_shared<::Type>(::TypeTag::Any)); return result;\n',
        '        }\n',
        '        if (method_name == "append") {\n',
        '            Reg arg_reg = emit_expr(*expr.arguments[0]); Reg result = allocate_register();\n',
        '            emit_instruction(LIR_Inst(LIR_Op::ListAppend, Type::Void, result, object_reg, arg_reg));\n',
        '            set_register_type(result, std::make_shared<::Type>(::TypeTag::Nil)); return result;\n',
        '        }\n',
        '        if (method_name == "len") {\n',
        '            Reg result = allocate_register(); emit_instruction(LIR_Inst(LIR_Op::ListLen, Type::I64, result, object_reg));\n',
        '            set_register_type(result, std::make_shared<::Type>(::TypeTag::Int)); return result;\n',
        '        }\n',
        '        report_error("Unknown method: " + method_name); return 0;\n',
        '    } else {\n',
        '        report_error("Complex function calls not yet supported in LIR"); return 0;\n',
        '    }\n',
        '}\n',
        '\n',
        '\n'
    ]
    lines[start_line:end_line] = new_func
    with open('src/lir/generator/expressions.cpp', 'w') as f:
        f.writelines(lines)
    print("Successfully replaced emit_call_expr")
else:
    print(f"Markers not found: start_line={start_line}, end_line={end_line}")
