# Created by and for Qt Creator This file was created for editing the project sources only.
# You may attempt to use it for building too, by modifying this file here.

#TARGET = Luminar

QT = core gui widgets

HEADERS = \
   $$PWD/src/backend/fyra/builder.hh \
   $$PWD/src/backend/fyra/fyra.hh \
   $$PWD/src/backend/fyra/fyra_builtin_functions.hh \
   $$PWD/src/backend/fyra/fyra_ir_generator.hh \
   $$PWD/src/backend/vm/register.hh \
   $$PWD/src/backend/big_int.hh \
   $$PWD/src/backend/channel.hh \
   $$PWD/src/backend/env.hh \
   $$PWD/src/backend/fiber.hh \
   $$PWD/src/backend/register_value.hh \
   $$PWD/src/backend/scheduler.hh \
   $$PWD/src/backend/shared_cell.hh \
   $$PWD/src/backend/symbol_table.hh \
   $$PWD/src/backend/task.hh \
   $$PWD/src/backend/types.hh \
   $$PWD/src/backend/value.hh \
   $$PWD/src/error/debugger.hh \
   $$PWD/src/error/message.hh \
   $$PWD/src/frontend/ast/builder.hh \
   $$PWD/src/frontend/ast/printer.hh \
   $$PWD/src/frontend/cst/printer.hh \
   $$PWD/src/frontend/cst/utils.hh \
   $$PWD/src/frontend/ast.hh \
   $$PWD/src/frontend/cst.hh \
   $$PWD/src/frontend/memory_checker.hh \
   $$PWD/src/frontend/module_manager.hh \
   $$PWD/src/frontend/parser.hh \
   $$PWD/src/frontend/scanner.hh \
   $$PWD/src/frontend/type_checker.hh \
   $$PWD/src/lir/builtin_functions.hh \
   $$PWD/src/lir/function_registry.hh \
   $$PWD/src/lir/functions.hh \
   $$PWD/src/lir/generator.hh \
   $$PWD/src/lir/lir.hh \
   $$PWD/src/lir/metrics.hh \
   $$PWD/src/lir/optimizer.hh \
   $$PWD/src/lir/serializer.hh \
   $$PWD/src/memory/analyzer.hh \
   $$PWD/src/memory/compiler.hh \
   $$PWD/src/memory/memory.hh \
   $$PWD/src/memory/model.hh \
   $$PWD/src/memory/runtime.hh \
   $$PWD/src/runtime/runtime.h \
   $$PWD/src/runtime/runtime_dict.h \
   $$PWD/src/runtime/runtime_list.h \
   $$PWD/src/runtime/runtime_string.h \
   $$PWD/src/runtime/runtime_tuple.h \
   $$PWD/src/runtime/runtime_value.h \
   $$PWD/src/runtime/runtime_value_base.h \
   $$PWD/src/limitly.hh \
   $$PWD/vendor/fyra/include/codegen/abi/ABIAnalysis.h \
   $$PWD/vendor/fyra/include/codegen/asm/Assembler.h \
   $$PWD/vendor/fyra/include/codegen/debug/DWARFGenerator.h \
   $$PWD/vendor/fyra/include/codegen/objectgen/ObjectFileGenerator.h \
   $$PWD/vendor/fyra/include/codegen/objectgen/PlatformGenerators.h \
   $$PWD/vendor/fyra/include/codegen/optimize/InstructionFusion.h \
   $$PWD/vendor/fyra/include/codegen/profiling/RuntimeProfiler.h \
   $$PWD/vendor/fyra/include/codegen/regalloc/LinearScanAllocator.h \
   $$PWD/vendor/fyra/include/codegen/regalloc/LiveInterval.h \
   $$PWD/vendor/fyra/include/codegen/regalloc/LiveIntervalAnalysis.h \
   $$PWD/vendor/fyra/include/codegen/regalloc/LivenessAnalysis.h \
   $$PWD/vendor/fyra/include/codegen/regalloc/RegAllocRewriter.h \
   $$PWD/vendor/fyra/include/codegen/validation/ASMValidator.h \
   $$PWD/vendor/fyra/include/codegen/validation/TargetABIRegistry.h \
   $$PWD/vendor/fyra/include/codegen/validation/ValidationTypes.h \
   $$PWD/vendor/fyra/include/codegen/CodeGen.h \
   $$PWD/vendor/fyra/include/ir/BasicBlock.h \
   $$PWD/vendor/fyra/include/ir/Constant.h \
   $$PWD/vendor/fyra/include/ir/Function.h \
   $$PWD/vendor/fyra/include/ir/FunctionType.h \
   $$PWD/vendor/fyra/include/ir/GlobalValue.h \
   $$PWD/vendor/fyra/include/ir/GlobalVariable.h \
   $$PWD/vendor/fyra/include/ir/Instruction.h \
   $$PWD/vendor/fyra/include/ir/IRBuilder.h \
   $$PWD/vendor/fyra/include/ir/IRContext.h \
   $$PWD/vendor/fyra/include/ir/Module.h \
   $$PWD/vendor/fyra/include/ir/Parameter.h \
   $$PWD/vendor/fyra/include/ir/PhiNode.h \
   $$PWD/vendor/fyra/include/ir/SIMDInstruction.h \
   $$PWD/vendor/fyra/include/ir/Syscall.h \
   $$PWD/vendor/fyra/include/ir/Type.h \
   $$PWD/vendor/fyra/include/ir/Use.h \
   $$PWD/vendor/fyra/include/ir/User.h \
   $$PWD/vendor/fyra/include/ir/Value.h \
   $$PWD/vendor/fyra/include/parser/Lexer.h \
   $$PWD/vendor/fyra/include/parser/Parser.h \
   $$PWD/vendor/fyra/include/target/architecture/aarch64/AArch64Architecture.h \
   $$PWD/vendor/fyra/include/target/architecture/riscv64/RiscV64Architecture.h \
   $$PWD/vendor/fyra/include/target/architecture/wasm32/Wasm32Architecture.h \
   $$PWD/vendor/fyra/include/target/architecture/wasm32/WasmBinary.h \
   $$PWD/vendor/fyra/include/target/architecture/x64/X64Architecture.h \
   $$PWD/vendor/fyra/include/target/artifact/apk/APKArtifact.h \
   $$PWD/vendor/fyra/include/target/artifact/apk/APKPackager.h \
   $$PWD/vendor/fyra/include/target/artifact/apk/JavaStubGen.h \
   $$PWD/vendor/fyra/include/target/artifact/apk/ManifestGen.h \
   $$PWD/vendor/fyra/include/target/artifact/executable/assembler.hh \
   $$PWD/vendor/fyra/include/target/artifact/executable/binary_writer.hh \
   $$PWD/vendor/fyra/include/target/artifact/executable/elf.hh \
   $$PWD/vendor/fyra/include/target/artifact/executable/macho.hh \
   $$PWD/vendor/fyra/include/target/artifact/executable/pe.hh \
   $$PWD/vendor/fyra/include/target/artifact/executable/platform_utils.hh \
   $$PWD/vendor/fyra/include/target/capabilities/Capabilities.h \
   $$PWD/vendor/fyra/include/target/core/ArchitectureInfo.h \
   $$PWD/vendor/fyra/include/target/core/CompositeTargetInfo.h \
   $$PWD/vendor/fyra/include/target/core/OperatingSystemInfo.h \
   $$PWD/vendor/fyra/include/target/core/TargetDescriptor.h \
   $$PWD/vendor/fyra/include/target/core/TargetInfo.h \
   $$PWD/vendor/fyra/include/target/core/TargetResolver.h \
   $$PWD/vendor/fyra/include/target/os/android/AndroidOS.h \
   $$PWD/vendor/fyra/include/target/os/linux/LinuxOS.h \
   $$PWD/vendor/fyra/include/target/os/macos/MacOSOS.h \
   $$PWD/vendor/fyra/include/target/os/wasi/WASIOS.h \
   $$PWD/vendor/fyra/include/target/os/windows/WindowsOS.h \
   $$PWD/vendor/fyra/include/transforms/CFGBuilder.h \
   $$PWD/vendor/fyra/include/transforms/ControlFlowSimplification.h \
   $$PWD/vendor/fyra/include/transforms/CopyElimination.h \
   $$PWD/vendor/fyra/include/transforms/DeadInstructionElimination.h \
   $$PWD/vendor/fyra/include/transforms/DominanceFrontier.h \
   $$PWD/vendor/fyra/include/transforms/DominatorTree.h \
   $$PWD/vendor/fyra/include/transforms/ErrorReporter.h \
   $$PWD/vendor/fyra/include/transforms/GVN.h \
   $$PWD/vendor/fyra/include/transforms/LoopInvariantCodeMotion.h \
   $$PWD/vendor/fyra/include/transforms/Mem2Reg.h \
   $$PWD/vendor/fyra/include/transforms/PassError.h \
   $$PWD/vendor/fyra/include/transforms/PhiInsertion.h \
   $$PWD/vendor/fyra/include/transforms/SCCP.h \
   $$PWD/vendor/fyra/include/transforms/SSARenamer.h \
   $$PWD/vendor/fyra/include/transforms/TransformPass.h \
   $$PWD/vendor/lyra/include/config_parser.hh \
   $$PWD/vendor/lyra/include/fetch_system.hh \
   $$PWD/vendor/lyra/include/handlers.hh \
   $$PWD/vendor/lyra/include/lock_system.hh \
   $$PWD/vendor/lyra/include/lyra_common.hh \
   $$PWD/vendor/lyra/include/process_helper.hh \
   $$PWD/vendor/lyra/include/registry_client.hh \
   $$PWD/vendor/lyra/include/resolver.hh \
   $$PWD/vendor/lyra/include/semver.hh \
   $$PWD/libLimitly.hh

SOURCES = \
   $$PWD/build_cmake/CMakeFiles/3.28.0-rc4/CompilerIdCXX/CMakeCXXCompilerId.cpp \
   $$PWD/src/backend/fyra/builder.cpp \
   $$PWD/src/backend/fyra/fyra.cpp \
   $$PWD/src/backend/fyra/fyra_builtin_functions.cpp \
   $$PWD/src/backend/fyra/fyra_ir_generator.cpp \
   $$PWD/src/backend/vm/register.cpp \
   $$PWD/src/backend/symbol_table.cpp \
   $$PWD/src/backend/value.cpp \
   $$PWD/src/error/debugger.cpp \
   $$PWD/src/frontend/ast/builder.cpp \
   $$PWD/src/frontend/ast/optimizer.cpp \
   $$PWD/src/frontend/ast/printer.cpp \
   $$PWD/src/frontend/cst/printer.cpp \
   $$PWD/src/frontend/cst/utils.cpp \
   $$PWD/src/frontend/parser/expressions.cpp \
   $$PWD/src/frontend/parser/patterns.cpp \
   $$PWD/src/frontend/parser/statements.cpp \
   $$PWD/src/frontend/parser/types.cpp \
   $$PWD/src/frontend/type_checker/core.cpp \
   $$PWD/src/frontend/type_checker/declarations.cpp \
   $$PWD/src/frontend/type_checker/expressions.cpp \
   $$PWD/src/frontend/type_checker/memory.cpp \
   $$PWD/src/frontend/type_checker/patterns.cpp \
   $$PWD/src/frontend/type_checker/statements.cpp \
   $$PWD/src/frontend/type_checker/types.cpp \
   $$PWD/src/frontend/type_checker/utils.cpp \
   $$PWD/src/frontend/cst.cpp \
   $$PWD/src/frontend/memory_checker.cpp \
   $$PWD/src/frontend/module_manager.cpp \
   $$PWD/src/frontend/parser.cpp \
   $$PWD/src/frontend/scanner.cpp \
   $$PWD/src/frontend/type_checker_factory.cpp \
   $$PWD/src/lir/generator/concurrency.cpp \
   $$PWD/src/lir/generator/core.cpp \
   $$PWD/src/lir/generator/expressions.cpp \
   $$PWD/src/lir/generator/modules.cpp \
   $$PWD/src/lir/generator/oop.cpp \
   $$PWD/src/lir/generator/signatures.cpp \
   $$PWD/src/lir/generator/statements.cpp \
   $$PWD/src/lir/builtin_functions.cpp \
   $$PWD/src/lir/function_registry.cpp \
   $$PWD/src/lir/functions.cpp \
   $$PWD/src/lir/generator.cpp \
   $$PWD/src/lir/lir.cpp \
   $$PWD/src/lir/lir_types.cpp \
   $$PWD/src/lir/lir_utils.cpp \
   $$PWD/src/lir/metrics.cpp \
   $$PWD/src/lir/optimizer.cpp \
   $$PWD/src/lir/serializer.cpp \
   $$PWD/src/runtime/runtime.c \
   $$PWD/src/runtime/runtime_dict.c \
   $$PWD/src/runtime/runtime_list.c \
   $$PWD/src/runtime/runtime_string.c \
   $$PWD/src/runtime/runtime_tuple.c \
   $$PWD/src/runtime/runtime_value.c \
   $$PWD/src/formatter.cpp \
   $$PWD/src/limitly.cpp \
   $$PWD/src/lsp.cpp \
   $$PWD/src/main.cpp \
   $$PWD/src/test_parser.cpp \
   $$PWD/vendor/fyra/examples/phpish_oop_inmemory.cpp \
   $$PWD/vendor/fyra/src/codegen/abi/ABIAnalysis.cpp \
   $$PWD/vendor/fyra/src/codegen/asm/Assembler.cpp \
   $$PWD/vendor/fyra/src/codegen/debug/DebugInfoManager.cpp \
   $$PWD/vendor/fyra/src/codegen/debug/DWARFGenerator.cpp \
   $$PWD/vendor/fyra/src/codegen/objectgen/ObjectFileGenerator.cpp \
   $$PWD/vendor/fyra/src/codegen/objectgen/PlatformGenerators.cpp \
   $$PWD/vendor/fyra/src/codegen/optimize/FusionCoordinator.cpp \
   $$PWD/vendor/fyra/src/codegen/optimize/InstructionFusion.cpp \
   $$PWD/vendor/fyra/src/codegen/profiling/RuntimeProfiler.cpp \
   $$PWD/vendor/fyra/src/codegen/regalloc/LinearScanAllocator.cpp \
   $$PWD/vendor/fyra/src/codegen/regalloc/LiveIntervalAnalysis.cpp \
   $$PWD/vendor/fyra/src/codegen/regalloc/LivenessAnalysis.cpp \
   $$PWD/vendor/fyra/src/codegen/regalloc/RegAllocRewriter.cpp \
   $$PWD/vendor/fyra/src/codegen/validation/ASMValidator.cpp \
   $$PWD/vendor/fyra/src/codegen/validation/TargetABIRegistry.cpp \
   $$PWD/vendor/fyra/src/codegen/validation/Validators.cpp \
   $$PWD/vendor/fyra/src/codegen/CodeGen.cpp \
   $$PWD/vendor/fyra/src/ir/BasicBlock.cpp \
   $$PWD/vendor/fyra/src/ir/Constant.cpp \
   $$PWD/vendor/fyra/src/ir/Function.cpp \
   $$PWD/vendor/fyra/src/ir/FunctionType.cpp \
   $$PWD/vendor/fyra/src/ir/GlobalVariable.cpp \
   $$PWD/vendor/fyra/src/ir/Instruction.cpp \
   $$PWD/vendor/fyra/src/ir/IRBuilder.cpp \
   $$PWD/vendor/fyra/src/ir/IRContext.cpp \
   $$PWD/vendor/fyra/src/ir/Module.cpp \
   $$PWD/vendor/fyra/src/ir/Parameter.cpp \
   $$PWD/vendor/fyra/src/ir/PhiNode.cpp \
   $$PWD/vendor/fyra/src/ir/SIMDInstruction.cpp \
   $$PWD/vendor/fyra/src/ir/Type.cpp \
   $$PWD/vendor/fyra/src/ir/Use.cpp \
   $$PWD/vendor/fyra/src/ir/User.cpp \
   $$PWD/vendor/fyra/src/ir/Value.cpp \
   $$PWD/vendor/fyra/src/parser/Lexer.cpp \
   $$PWD/vendor/fyra/src/parser/Parser.cpp \
   $$PWD/vendor/fyra/src/target/architecture/aarch64/AArch64Architecture.cpp \
   $$PWD/vendor/fyra/src/target/architecture/riscv64/RiscV64Architecture.cpp \
   $$PWD/vendor/fyra/src/target/architecture/wasm32/Wasm32Architecture.cpp \
   $$PWD/vendor/fyra/src/target/architecture/x64/X64Architecture.cpp \
   $$PWD/vendor/fyra/src/target/artifact/apk/APKArtifact.cpp \
   $$PWD/vendor/fyra/src/target/artifact/apk/APKPackager.cpp \
   $$PWD/vendor/fyra/src/target/artifact/apk/JavaStubGen.cpp \
   $$PWD/vendor/fyra/src/target/artifact/apk/ManifestGen.cpp \
   $$PWD/vendor/fyra/src/target/artifact/executable/binary_writer.cpp \
   $$PWD/vendor/fyra/src/target/artifact/executable/elf.cpp \
   $$PWD/vendor/fyra/src/target/artifact/executable/macho.cpp \
   $$PWD/vendor/fyra/src/target/artifact/executable/pe.cpp \
   $$PWD/vendor/fyra/src/target/artifact/executable/platform_utils.cpp \
   $$PWD/vendor/fyra/src/target/capabilities/CapabilityRegistry.cpp \
   $$PWD/vendor/fyra/src/target/core/ArchitectureInfo.cpp \
   $$PWD/vendor/fyra/src/target/core/CompositeTargetInfo.cpp \
   $$PWD/vendor/fyra/src/target/core/TargetDescriptor.cpp \
   $$PWD/vendor/fyra/src/target/core/TargetInfo.cpp \
   $$PWD/vendor/fyra/src/target/core/TargetResolver.cpp \
   $$PWD/vendor/fyra/src/target/os/linux/LinuxOS.cpp \
   $$PWD/vendor/fyra/src/target/os/macos/MacOSOS.cpp \
   $$PWD/vendor/fyra/src/target/os/wasi/WASIOS.cpp \
   $$PWD/vendor/fyra/src/target/os/windows/WindowsOS.cpp \
   $$PWD/vendor/fyra/src/transforms/CFGBuilder.cpp \
   $$PWD/vendor/fyra/src/transforms/ControlFlowSimplification.cpp \
   $$PWD/vendor/fyra/src/transforms/CopyElimination.cpp \
   $$PWD/vendor/fyra/src/transforms/DeadInstructionElimination.cpp \
   $$PWD/vendor/fyra/src/transforms/DominanceFrontier.cpp \
   $$PWD/vendor/fyra/src/transforms/DominatorTree.cpp \
   $$PWD/vendor/fyra/src/transforms/GVN.cpp \
   $$PWD/vendor/fyra/src/transforms/LoopInvariantCodeMotion.cpp \
   $$PWD/vendor/fyra/src/transforms/Mem2Reg.cpp \
   $$PWD/vendor/fyra/src/transforms/PhiInsertion.cpp \
   $$PWD/vendor/fyra/src/transforms/SCCP.cpp \
   $$PWD/vendor/fyra/src/transforms/SSARenamer.cpp \
   $$PWD/vendor/fyra/tests/CodeGen/wasm_inmemory_test.cpp \
   $$PWD/vendor/fyra/tests/fibonacci_wasm_test.cpp \
   $$PWD/vendor/fyra/tests/simple_wasm_test.cpp \
   $$PWD/vendor/fyra/tests/test_aarch64.cpp \
   $$PWD/vendor/fyra/tests/test_aarch64_capability_compliance.cpp \
   $$PWD/vendor/fyra/tests/test_add.cpp \
   $$PWD/vendor/fyra/tests/test_benchmark_suite.cpp \
   $$PWD/vendor/fyra/tests/test_capability_compliance.cpp \
   $$PWD/vendor/fyra/tests/test_codegen.cpp \
   $$PWD/vendor/fyra/tests/test_comprehensive.cpp \
   $$PWD/vendor/fyra/tests/test_control_flow.cpp \
   $$PWD/vendor/fyra/tests/test_copy_elimination.cpp \
   $$PWD/vendor/fyra/tests/test_div.cpp \
   $$PWD/vendor/fyra/tests/test_extern.cpp \
   $$PWD/vendor/fyra/tests/test_float.cpp \
   $$PWD/vendor/fyra/tests/test_functions.cpp \
   $$PWD/vendor/fyra/tests/test_http_server.cpp \
   $$PWD/vendor/fyra/tests/test_inmemory_aarch64_exec.cpp \
   $$PWD/vendor/fyra/tests/test_macos_aarch64_capability_compliance.cpp \
   $$PWD/vendor/fyra/tests/test_mul.cpp \
   $$PWD/vendor/fyra/tests/test_parser.cpp \
   $$PWD/vendor/fyra/tests/test_pe_generator.cpp \
   $$PWD/vendor/fyra/tests/test_phpish_frontend.cpp \
   $$PWD/vendor/fyra/tests/test_portable_capabilities.cpp \
   $$PWD/vendor/fyra/tests/test_riscv64.cpp \
   $$PWD/vendor/fyra/tests/test_sqlite_clone.cpp \
   $$PWD/vendor/fyra/tests/test_sqlite_emulation.cpp \
   $$PWD/vendor/fyra/tests/test_ssa.cpp \
   $$PWD/vendor/fyra/tests/test_sub.cpp \
   $$PWD/vendor/fyra/tests/test_voilet_frontend.cpp \
   $$PWD/vendor/fyra/tests/test_wasm32.cpp \
   $$PWD/vendor/fyra/tests/test_windows.cpp \
   $$PWD/vendor/fyra/tests/test_windows_aarch64_capability_compliance.cpp \
   $$PWD/vendor/fyra/tests/test_windows_capability_compliance.cpp \
   $$PWD/vendor/fyra/main.cpp \
   $$PWD/vendor/lyra/src/build.cpp \
   $$PWD/vendor/lyra/src/init.cpp \
   $$PWD/vendor/lyra/src/main.cpp \
   $$PWD/vendor/lyra/src/registry.cpp \
   $$PWD/vendor/lyra/src/run.cpp \
   $$PWD/vendor/lyra/src/tooling.cpp \
   $$PWD/vendor/lyra/src/update.cpp

INCLUDEPATH = \
    $$PWD/src/runtime \
    $$PWD/vendor/fyra/include/codegen \
    $$PWD/vendor/fyra/include/codegen/abi \
    $$PWD/vendor/fyra/include/codegen/asm \
    $$PWD/vendor/fyra/include/codegen/debug \
    $$PWD/vendor/fyra/include/codegen/objectgen \
    $$PWD/vendor/fyra/include/codegen/optimize \
    $$PWD/vendor/fyra/include/codegen/profiling \
    $$PWD/vendor/fyra/include/codegen/regalloc \
    $$PWD/vendor/fyra/include/codegen/validation \
    $$PWD/vendor/fyra/include/ir \
    $$PWD/vendor/fyra/include/parser \
    $$PWD/vendor/fyra/include/target/architecture/aarch64 \
    $$PWD/vendor/fyra/include/target/architecture/riscv64 \
    $$PWD/vendor/fyra/include/target/architecture/wasm32 \
    $$PWD/vendor/fyra/include/target/architecture/x64 \
    $$PWD/vendor/fyra/include/target/artifact/apk \
    $$PWD/vendor/fyra/include/target/capabilities \
    $$PWD/vendor/fyra/include/target/core \
    $$PWD/vendor/fyra/include/target/os/android \
    $$PWD/vendor/fyra/include/target/os/linux \
    $$PWD/vendor/fyra/include/target/os/macos \
    $$PWD/vendor/fyra/include/target/os/wasi \
    $$PWD/vendor/fyra/include/target/os/windows \
    $$PWD/vendor/fyra/include/transforms

#DEFINES = 

