// One layout definition for the host and generated native modules.
LM_NATIVE_OP(uint64_t, frame_get, (void*, uint64_t, uint32_t, bool))
LM_NATIVE_OP(uint64_t, frame_set, (void*, uint64_t, uint32_t, uint64_t, bool))
LM_NATIVE_OP(uint64_t, sequence_get, (uint64_t, int64_t))
LM_NATIVE_OP(uint64_t, sequence_set, (void*, uint64_t, uint64_t, uint64_t))
LM_NATIVE_OP(uint64_t, list_append, (void*, uint64_t, uint64_t))
LM_NATIVE_OP(uint64_t, list_length, (uint64_t))
LM_NATIVE_OP(uint64_t, dict_get, (uint64_t, uint64_t))
LM_NATIVE_OP(uint64_t, dict_has, (uint64_t, uint64_t))
LM_NATIVE_OP(uint64_t, dict_length, (uint64_t))
LM_NATIVE_OP(uint64_t, string_index, (uint64_t, int64_t))
LM_NATIVE_OP(uint64_t, string_contains, (uint64_t, uint64_t))
LM_NATIVE_OP(uint64_t, string_starts_with, (uint64_t, uint64_t))
LM_NATIVE_OP(uint64_t, string_ends_with, (uint64_t, uint64_t))
LM_NATIVE_OP(uint64_t, string_index_of, (uint64_t, uint64_t))
LM_NATIVE_OP(uint64_t, string_byte_length, (uint64_t))
LM_NATIVE_OP(uint64_t, string_byte_at, (uint64_t, int64_t))
