#include "generator/core.cpp"
#include "generator/signatures.cpp"
#include "generator/oop.cpp"
#include "generator/modules.cpp"
#include "generator/expressions.cpp"
#include "generator/statements.cpp"
#include "generator/concurrency.cpp"
